service: books-api

# app and org for use with dashboard.serverless.com
app: my-first-app
org: ivanchuchman

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  app:
    handler: dist/app.handler
    events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          cors: true
          path: '/{any+}'
          method: any

custom:
  serverless-offline:
    noPrependStageInUrl: true